apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kfe3noecd-java-springboot 
  janus-idp.io/tekton: kfe3noecd-java-springboot
  backstage.io/kubernetes-id: kfe3noecd-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kfe3noecd-java-springboot
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml